version: '2'

services:
  proxy:
    image: traefik:latest
    container_name: traefik
    restart: always
    command: --docker.domain="${DOCKER_DOMAIN}" --acme.email="${ACME_EMAIL}"
    networks:
    - web
    ports:
    - 80:80
    - 443:443
    - 8080:8080
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    - ./traefik.toml:/traefik.toml
    - ./acme/acme.json:/acme.json
networks:
  web:
    external: true
