################################################################
# Global configuration
################################################################

# Enable debug mode
# debug = true

# Log level
logLevel = "INFO"

defaultEntryPoints = ["http", "https"]

[api]

[acme]
email = "nick@tam.er" # Just set that as a CLI argument!
storage = "acme.json"
acmeLogging = true
OnHostRule=true
entryPoint = "https"
[acme.httpChallenge]
entryPoint = "http"

[entryPoints]
  [entryPoints.traefik]
  address = ":8080"
  [entryPoints.traefik.auth]
     [entryPoints.traefik.auth.digest]
       users = ["REPLACE_ME"]
  [entryPoints.http]
  address = ":80"
    [entryPoints.http.redirect]
    entryPoint = "https"
  [entryPoints.https]
  address = ":443"
  [entryPoints.https.tls]

[retry]

# Enable Docker configuration backend
[docker]
endpoint = "unix:///var/run/docker.sock"
watch = true
exposedByDefault = false

[metrics]
  [metrics.prometheus]
    entryPoint = "traefik"

